name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Install Qwik Static Adapter
        run: pnpm qwik add static --no-install

      - name: Configure Static Adapter
        run: |
          # Extract repository name from github.repository
          REPO_NAME=$(echo ${{ github.repository }} | cut -d'/' -f2)
          
          # Update the origin URL in the static adapter config to use GitHub environment variables
          sed -i 's|origin: "https://yoursite.qwik.dev"|origin: "https://${{ github.repository_owner }}.github.io/'$REPO_NAME'"|' adapters/static/vite.config.ts
          
          # Fix the base path duplication by setting the main vite.config.ts base to '/'
          # when the static adapter is being used
          sed -i 's|base: process.env.GITHUB_REPOSITORY|base: process.env.STATIC_ADAPTER ? "/" : process.env.GITHUB_REPOSITORY|' vite.config.ts

      - name: Build
        run: pnpm build
        env:
          # This ensures the base path is set correctly for GitHub Pages
          GITHUB_REPOSITORY: ${{ github.repository }}
          STATIC_ADAPTER: true

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
